# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [1]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np
answer(1)

import numpy as np


#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
# 打印 numpy 的版本号
print(np.__version__)

# 打印 numpy 的配置信息
np.show_config()

answer(2)

2.3.1
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/cuixinzhe/.conda/envs/kaggle-house/Library/include
    lib directory: C:/Users/cuixinzhe/.conda/envs/kaggle-house/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_958d_utj4g\croot\numpy_and_numpy_base_1750883811830\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/cuixinzhe/.conda/envs/kaggle-house/Library/include
    lib directory: C:/Users/cuixinzhe/.conda/envs/kaggle-house/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_958d_utj4g\croot\numpy_and_numpy_base_1750883811830\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version:

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
Z = np.zeros(10)
print(Z)
answer(3)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Z = np.zeros(10)
print(Z)


#### 4. How to find the memory size of any array (★☆☆)

In [5]:
print(f"{Z.nbytes} bytes")
answer(4)

80 bytes
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

# Simpler alternative
print("%d bytes" % Z.nbytes)


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
help(np.add)
answer(5)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])
    
    Add arguments element-wise.
    
    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` 

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
Z = np.zeros(10)
Z[4] = 1
print(Z)
answer(6)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Z = np.zeros(10)
Z[4] = 1
print(Z)


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
Z = np.arange(10, 50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [9]:
Z = np.arange(50)
Z = np.flip(Z,axis = 0)
print(Z)
answer(8)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]
Z = np.arange(50)
Z = Z[::-1]
print(Z)


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
Z = np.arange(0,9).reshape(3,3)
print(Z)
answer(9)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
Z = np.arange(9).reshape(3, 3)
print(Z)


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
Z = np.array([1,2,0,0,4,0])
Z = np.nonzero(Z != 0)
print(Z)
answer(10)

(array([0, 1, 4]),)
nz = np.nonzero([1,2,0,0,4,0])
print(nz)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
I = np.eye(3)
print(I)
answer(11)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Z = np.eye(3)
print(Z)


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
Z = np.random.random((3,3,3))
print(Z)
answer(12)

[[[0.81774798 0.42732199 0.74559417]
  [0.30828334 0.18669721 0.09759766]
  [0.72214339 0.11605043 0.443572  ]]

 [[0.33830653 0.69735688 0.91667229]
  [0.00943599 0.82139393 0.99302616]
  [0.79653869 0.53097006 0.15516761]]

 [[0.96488706 0.9608321  0.50199137]
  [0.00372959 0.51948568 0.1152661 ]
  [0.38009111 0.9037968  0.32594559]]]
Z = np.random.random((3,3,3))
print(Z)


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
Z = np.random.random((10,10))
Z_min = np.min(Z)
Z_max = np.max(Z)
print(Z_min,Z_max)
answer(13)

0.012844260415169284 0.9989809048954367
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()
print(Zmin, Zmax)


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
Z = np.random.random(30)
Z_mean = np.mean(Z)
print(Z_mean)
answer(14)

0.5453453602819264
Z = np.random.random(30)
m = Z.mean()
print(m)


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)
answer(15)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
Z = np.ones((10,10))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)
answer(16)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

# Using fancy indexing
Z[:, [0, -1]] = 0
Z[[0, -1], :] = 0
print(Z)


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [18]:
0 * np.nan # 结果是 nan
np.nan == np.nan # 结果是 False
np.inf > np.nan # 结果是 False 
np.nan - np.nan # 结果是 nan
np.nan in set([np.nan]) # 结果是 True
0.3 == 3 * 0.1 # 结果是 False
answer(17)


print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
Z =np.diag([1,2,3,4])
Z = np.pad(Z, ((1,0),(0,1)), mode='constant', constant_values=0)
print(Z)
answer(18)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]
Z = np.diag(1+np.arange(4),k=-1)
print(Z)


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
Z = np.zeros((8,8), dtype=int) 
Z[1::2, ::2] = 1 
Z[::2, 1::2] = 1 
print(Z)
answer(19)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [21]:
print(np.unravel_index(99,(6,7,8)))
answer(20)

(np.int64(1), np.int64(5), np.int64(3))
print(np.unravel_index(99,(6,7,8)))


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [22]:
b = np.array([[0,1],[1,0]])
print(np.tile(b,(4,4)))
answer(21)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [23]:
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)
answer(22)

[[ 0.78533971 -0.61985212 -0.62920031  0.68550941 -1.10023615]
 [ 1.80060543 -0.31092648  1.27490961 -1.09834476  0.38784439]
 [ 0.77098451  1.44652234  0.14838832  1.29067137 -0.51058895]
 [-0.33646284 -1.72405412 -0.2709847  -0.30325253 -1.21819191]
 [-0.80612735  1.70223783 -0.62831515 -1.3726951   0.63621954]]
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])
answer(23)

color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [25]:
#矩阵乘法用运算符 @
answer(24)

Z = np.matmul(np.ones((5, 3)), np.ones((3, 2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))
print(Z)


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [26]:
Z = np.arange(11)
index =(Z > 3) & (Z < 8)
Z[index] *= -1
print(Z)
answer(25)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]
# Author: Evgeni Burovski

Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [28]:
# Z ** Z legal
# 2 << Z >> 2 legal
# Z <- Z illeagal
# 1j*Z legal
# Z/1/1 legal
# Z<Z>Z legal
answer(27)

Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [29]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))
answer(28)

nan
0
[-9.22337204e+18]
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))


C:\Users\cuixinzhe\AppData\Local\Temp\ipykernel_50080\2948226861.py:1: RuntimeWarning: invalid value encountered in divide
  print(np.array(0) / np.array(0))
C:\Users\cuixinzhe\AppData\Local\Temp\ipykernel_50080\2948226861.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))
C:\Users\cuixinzhe\AppData\Local\Temp\ipykernel_50080\2948226861.py:3: RuntimeWarning: invalid value encountered in cast
  print(np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [30]:
Z = np.random.uniform(-10,+10,10)
res = np.where(Z>0,np.ceil(Z),np.floor(Z)) #ceil 向上取整 floor 向下取整
print(Z)
print(res)
answer(29)

[-1.74808047  4.55662759  3.22123215 -9.78710526 -1.37497877 -7.81388903
  7.13087811 -2.00395064 -3.17151476  1.25095461]
[ -2.   5.   4. -10.  -2.  -8.   8.  -3.  -4.   2.]
# Author: Charles R Harris

Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))

# More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))


#### 30. How to find common values between two arrays? (★☆☆)

In [31]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [32]:
defaults = np.seterr(all="ignore")
answer(31)

# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all="ignore"):
    np.arange(3) / 0


#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [33]:
#False
#np.sqrt()本质处理实数域问题
#np.emath.sqrt()是一个延展数域的处理
print(np.sqrt(-1)==np.emath.sqrt(-1))
answer(32)

False
np.sqrt(-1) == np.emath.sqrt(-1)


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [34]:
a = timedelta64(1,"D")
today = datetime64("2025-09-08")
tomorrow = today + a
print(tomorrow)
yesterday = today - a 
print(yesterday)
answer(33)

2025-09-09
2025-09-07
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [35]:
date = np.arange(np.datetime64('2016-07-01'),np.datetime64('2016-07-31'),np.timedelta64(1,"D"))
print(date)
answer(34)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30']
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [36]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)
answer(35)

[-1.5 -1.5 -1.5]
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [37]:
Z = np.random.uniform(0, 10, 5)
Z1 = np.floor(Z)
Z2 = Z // 1
Z3 = Z.astype(int)
Z4 = np.trunc(Z)
print(Z)
print(Z1)
print(Z2)
print(Z3)
print(Z4)

[8.9711703  1.71102261 3.29402233 6.02619907 0.92890504]
[8. 1. 3. 6. 0.]
[8. 1. 3. 6. 0.]
[8 1 3 6 0]
[8. 1. 3. 6. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [38]:
a = np.arange(5)
A = np.tile(a, (5, 1))
print(A)
answer(37)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

# without broadcasting
Z = np.tile(np.arange(0, 5), (5,1))
print(Z)


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [39]:
def gen():
    for i in range(10):
        yield i 
Z = np.fromiter(gen(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [40]:
Z = np.linspace(0, 1, 11, endpoint=False)[1:]
print(Z)
answer(39)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [41]:
Z = np.random.random(10)
Z.sort()
print(Z)
answer(40)

[0.00271043 0.10811505 0.12400579 0.16902021 0.43886766 0.49842181
 0.66612125 0.80743293 0.86790092 0.87875456]
Z = np.random.random(10)
Z.sort()
print(Z)


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [42]:
Z = np.arange(10)
np.add.reduce(Z)
answer(41)

# Author: Evgeni Burovski

Z = np.arange(10)
np.add.reduce(Z)


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [43]:
A =np.random.random(5)
B = np.random.random(5)
print(np.array_equal(A,B))
answer(42)

False
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)


#### 43. Make an array immutable (read-only) (★★☆)

In [44]:
answer(43)

Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [45]:
answer(44)

Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [46]:
Z = np.random.random(10)
Z[Z==Z.max()] = 0
print(Z)

[0.38387589 0.51296695 0.         0.29309888 0.32567898 0.17649486
 0.6621056  0.02783964 0.42065523 0.12105762]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [47]:
xy = np.dtype([("x", float), ("y", float)])
answer(46)

Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [48]:
X = np.arange(1, 6)
Y = np.arange(6, 11)

C = 1.0 / (X[:, None] - Y[None, :])
print(C)
answer(47)

[[-0.2        -0.16666667 -0.14285714 -0.125      -0.11111111]
 [-0.25       -0.2        -0.16666667 -0.14285714 -0.125     ]
 [-0.33333333 -0.25       -0.2        -0.16666667 -0.14285714]
 [-0.5        -0.33333333 -0.25       -0.2        -0.16666667]
 [-1.         -0.5        -0.33333333 -0.25       -0.2       ]]
# Author: Evgeni Burovski

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y)
print(np.linalg.det(C))


#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [49]:
answer(48)
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)  # 浮点数最小精度（两个数能区分开的最小差距）

for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)
-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [50]:
answer(49)
np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)

np.set_printoptions(threshold=float("inf"))
Z = np.zeros((40,40))
print(Z)
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [51]:
Z = np.random.uniform(0, 10, 10)   # 一个随机向量
target = 5                         # 给定标量

# 计算每个元素与 target 的差值绝对值
diff = np.abs(Z - target)

# 找到最小差值的索引
idx = diff.argmin()

# 取出对应的最接近值
closest_value = Z[idx]

print("向量:", Z)
print("目标:", target)
print("最接近的值:", closest_value)
answer(50)

向量: [6.74784691 0.09798673 6.7720608  7.00930354 1.85791514 4.40371775
 2.30753699 3.20905396 6.11720742 9.00014722]
目标: 5
最接近的值: 4.403717746249632
Z = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(Z-v)).argmin()
print(Z[index])


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [52]:
n = np.dtype([
    ('position', [('X', np.float64), ('Y', np.float64)]),   # 分组 position
    ('color', [('r', np.uint8), ('g', np.uint8), ('b', np.uint8)])  # 分组 color
])
Z = np.zeros((10,), dtype=n)
print(Z)
answer(51)

[((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0)) ((0., 0.), (0, 0, 0))
 ((0., 0.), (0, 0, 0))]
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [53]:
import scipy
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)
answer(52)

[[0.         0.68776024 0.71050868 0.1479036  0.49997011 0.82056382
  0.9904241  0.38113064 0.60042167 0.2091741 ]
 [0.68776024 0.         0.2806083  0.65214777 0.66722448 0.35824356
  0.4452115  0.70471833 0.21057413 0.75202949]
 [0.71050868 0.2806083  0.         0.73346944 0.48580002 0.63880391
  0.27994179 0.57267458 0.46250934 0.69289442]
 [0.1479036  0.65214777 0.73346944 0.         0.61525639 0.72235914
  1.00856247 0.51111225 0.52451892 0.35569438]
 [0.49997011 0.66722448 0.48580002 0.61525639 0.         0.97393414
  0.71473097 0.1428035  0.73530358 0.34565839]
 [0.82056382 0.35824356 0.63880391 0.72235914 0.97393414 0.
  0.75843616 0.97491418 0.24317662 0.95691554]
 [0.9904241  0.4452115  0.27994179 1.00856247 0.71473097 0.75843616
  0.         0.82459161 0.65565953 0.96493085]
 [0.38113064 0.70471833 0.57267458 0.51111225 0.1428035  0.97491418
  0.82459161 0.         0.73181084 0.20600629]
 [0.60042167 0.21057413 0.46250934 0.52451892 0.73530358 0.24317662
  0.65565953 0.73181

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [54]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.astype(np.int32)
print(Y)
answer(53)

[74 62 69 15 30 30 87 67 31 53]
# Thanks Vikas (https://stackoverflow.com/a/10622758/5989906)
# & unutbu (https://stackoverflow.com/a/4396247/5989906)
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [55]:
answer(54)

from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [56]:
answer(55)

Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [57]:
# 定义大小
x, y = np.meshgrid(np.linspace(-1, 1, 10), np.linspace(-1, 1, 10))

# 定义sigma
sigma = 0.5
G = np.exp(-(x**2 + y**2) / (2 * sigma**2))

print(G)

answer(56)

[[0.01831564 0.0403616  0.07300087 0.10836802 0.13203459 0.13203459
  0.10836802 0.07300087 0.0403616  0.01831564]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0.16086971 0.08894358 0.0403616 ]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.13203459 0.29096046 0.52625189 0.7812082  0.95181678 0.95181678
  0.7812082  0.52625189 0.29096046 0.13203459]
 [0.10836802 0.2388072  0.43192377 0.64118039 0.7812082  0.7812082
  0.64118039 0.43192377 0.2388072  0.10836802]
 [0.07300087 0.16086971 0.29096046 0.43192377 0.52625189 0.52625189
  0.43192377 0.29096046 0.16086971 0.07300087]
 [0.0403616  0.08894358 0.16086971 0.2388072  0.29096046 0.29096046
  0.2388072  0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [58]:
Z = np.ones((5,5))
p = 5
Z = Z.flatten()
index = np.random.choice(range(Z.size), p, replace=False)
Z[index] = 0
Z = Z.reshape((5,5))
print(Z)
answer(57)

[[1. 1. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [0. 1. 1. 0. 1.]
 [1. 0. 0. 1. 1.]]
# Author: Divakar

n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [59]:
Z = np.random.rand(5,5)
row_means = Z.mean(axis=1, keepdims=True)
Z_centered = Z - row_means
print(Z_centered)
answer(58)

[[ 0.37362301  0.24508967 -0.20099811 -0.3041924  -0.11352217]
 [ 0.25491744 -0.14049373 -0.00457355  0.02758814 -0.1374383 ]
 [ 0.34821428 -0.11167475 -0.25946706 -0.29444554  0.31737307]
 [ 0.1269127  -0.3348189   0.40862629 -0.22724252  0.02652242]
 [-0.23582046 -0.01412154  0.40066688 -0.34088344  0.19015856]]
# Author: Warren Weckesser

X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)


#### 59. How to sort an array by the nth column? (★★☆)

In [60]:
Z = np.random.rand(5, 5)   # 随机生成一个 5x5 数组
n = 2                      # 比如按第 3 列排序（索引从 0 开始）

sorted_Z = Z[Z[:, n].argsort()]
print(sorted_Z)

[[0.60593693 0.31148437 0.20586064 0.19744986 0.43366812]
 [0.80719633 0.03973331 0.20653906 0.06269695 0.12983685]
 [0.37461098 0.56221047 0.26199005 0.52047313 0.34588294]
 [0.73858311 0.6507902  0.66177272 0.40085956 0.07703922]
 [0.24260894 0.27804273 0.72152565 0.79213435 0.99757607]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [61]:
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))
answer(60)

[False False  True]
# Author: Warren Weckesser

# null : 0 
Z = np.random.randint(0,3,(3,10))
print((~Z.any(axis=0)).any())

# null : np.nan
Z=np.array([
    [0,1,np.nan],
    [1,2,np.nan],
    [4,5,np.nan]
])
print(np.isnan(Z).all(axis=0))


#### 61. Find the nearest value from a given value in an array (★★☆)

In [62]:
Z = np.random.randint(0,10,(3,3))
A = 5
diff = np.abs(Z - A)
index = diff.argmin()
print(Z.flat[index])
print(Z)
answer(61) 

6
[[8 2 0]
 [6 9 8]
 [1 6 6]]
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [63]:
answer(62)

A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])


#### 63. Create an array class that has a name attribute (★★☆)

In [64]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)
answer(63)

range_10
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [65]:
# np.add.at(array, indices, values)
answer(64)

# Author: Brett Olsen

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
# Author: Bartosz Telenczuk
np.add.at(Z, I, 1)
print(Z)


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [66]:
#Also, np.add.at(F,I,X)
answer(65)

# Author: Alan G Isaac

X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [67]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)
answer(66)

64
# Author: Fisher Wang

w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
# Author: Mark Setchell
# https://stackoverflow.com/a/59671950/2836621

w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [68]:
#sum(axis=(-2,-1))
answer(67)

A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [69]:
answer(68)

# Author: Jaime Fernández del Río

D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

# Pandas solution as a reference due to more intuitive code
import pandas as pd
print(pd.Series(D).groupby(S).mean())


#### 69. How to get the diagonal of a dot product? (★★★)

In [70]:
#np.sum(A * B.T, axis=1)
#一个数学上的巧思
answer(69)

# Author: Mathieu Blondel

A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [71]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z #隔nz+1插入原数组
print(Z0)
answer(70)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]
# Author: Warren Weckesser

Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)


#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

In [72]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])
answer(71)

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])


#### 72. How to swap two rows of an array? (★★★)

In [73]:
# np能一步到位
# Z [[i,j]] = Z[[j,i]] 行交换
# Z[:,[i,j]] = Z[:,[j,i]] 列交换
answer(72)


# Author: Eelco Hoogendoorn

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [74]:
import numpy as np

# T: 每行是一个三角形的三个顶点索引
T = np.array([
    [0, 1, 2],
    [2, 1, 3],
    [0, 2, 3]
], dtype=int)

# 列出每个三角形的3条边：(0,1),(1,2),(2,0)
edges = np.vstack([T[:,[0,1]], T[:,[1,2]], T[:,[2,0]]])   # 形状 (3*n, 2)

# 将每条边内部排序，解决 (x,y) 与 (y,x) 等价
edges = np.sort(edges, axis=1)

# 按行唯一化，得到所有不重复的边
unique_edges = np.unique(edges, axis=0)
print(unique_edges)

answer(73)

[[0 1]
 [0 2]
 [0 3]
 [1 2]
 [1 3]
 [2 3]]
# Author: Nicolas P. Rougier

faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [75]:
#A = np.repeat(np.arange(len(C)), C)
answer(74)

# Author: Jaime Fernández del Río

C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [76]:
answer(75)

# Author: Jaime Fernández del Río

def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

# Author: Jeff Luo (@Jeff1999)
# make sure your NumPy >= 1.20.0

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [77]:
#使用sliding_window_view
answer(76)

# Author: Joe Kington / Erik Rigtorp
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

# Author: Jeff Luo (@Jeff1999)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)